name: Generate Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:  # Allows to manually run the job at any time
  push:
    branches:
      - main  # Use 'main' or 'master', depending on your default branch

jobs:
  generate:
    permissions:
      contents: write  # Ensure permissions to push to the branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate GitHub Contribution Grid Snake SVG
      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Ensure this is your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the generated files to the 'output' branch
      - name: Push GitHub Contribution Grid Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
